---
project:
  resources:
    - assets
  type: website

format:
  html:
    theme: superhero

website:
  google-analytics: G-397WWHGNV5
  favicon: /assets/images/favicon.ico
  navbar:
    tools:
      - icon: house
        href: https://paddyroddy.github.io
      - icon: github
        href: https://github.com/paddyroddy/posters
  site-url: https://paddyroddy.github.io/posters
  title: ""
