---
project:
  type: website

format:
  html:
    theme: superhero
  poster-typst:
    filters:
      - _filters/slugify.lua
    footer-text: "{{< meta subtitle >}}"
    footer-url: https://paddyroddy.github.io/posters/{{< meta slug >}}.qmd
    size: 36x24

website:
  google-analytics: G-397WWHGNV5
  favicon: /assets/images/favicon.ico
  navbar:
    tools:
      - icon: house
        href: https://paddyroddy.github.io
      - icon: github
        href: https://github.com/paddyroddy/posters
  title: ""
